version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:1.1.0
    environment:
      - ZEEBE_LOG_LEVEL=info
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ../lib/zeebe-hazelcast-exporter-1.0.0.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter-1.0.0.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network
  monitor:
    container_name: zeeqs
    image: camunda/zeeqs:latest
    environment:
      - zeebe.hazelcast.connection=zeebe:5701
    # volumes:
    #   - ./simple-monitor-application.yaml:/usr/local/zeebe/config/application.yaml
    ports:
      - "9001:9000"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
