version: "2"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe:0.20.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
    volumes:
      - ./zeebe-filtered-debug-exporter-1.0-SNAPSHOT.jar:/usr/local/zeebe/lib/zeebe-filtered-debug-exporter.jar
      - ./zeebe.cfg.toml:/usr/local/zeebe/conf/zeebe.cfg.toml
    networks:
      - zeebe_network
